const BOT_CONFIG = {
  host: '127.0.0.1',
  port: 1055,
  username: 'BotBuddy',
  auth: 'offline',
  version: '1.21.11'
};

const LM_STUDIO_BASE = 'http://127.0.0.1:1234/v1';
const LM_MODEL = 'qwen_qwen3-30b-a3b-instruct-2507';

const STORAGE_SEARCH_DISTANCE = 16;
const RESOURCE_SEARCH_DISTANCE = 32;
const RESOURCE_CANDIDATE_COUNT = 16;
const PLACEMENT_SEARCH_DISTANCE = 4;
const DEFAULT_WOOD_STOCK_TARGET = 64;
const WOOD_MAINTENANCE_CHECK_INTERVAL_MS = 30000;
const WOOD_MAINTENANCE_FAILURE_COOLDOWN_MS = 60000;

module.exports = {
  BOT_CONFIG,
  LM_STUDIO_BASE,
  LM_MODEL,
  DEFAULT_WOOD_STOCK_TARGET,
  RESOURCE_CANDIDATE_COUNT,
  STORAGE_SEARCH_DISTANCE,
  RESOURCE_SEARCH_DISTANCE,
  PLACEMENT_SEARCH_DISTANCE,
  WOOD_MAINTENANCE_CHECK_INTERVAL_MS,
  WOOD_MAINTENANCE_FAILURE_COOLDOWN_MS
};
