const TOOL_ERROR_CODES = {
  INVALID_TOOL_ARGS: 'INVALID_TOOL_ARGS',
  OBJECTIVE_BLOCKED: 'OBJECTIVE_BLOCKED',
  OBJECTIVE_LIMIT_REACHED: 'OBJECTIVE_LIMIT_REACHED',
  RUNTIME_BUSY: 'RUNTIME_BUSY',
  TOOL_NOT_ALLOWED: 'TOOL_NOT_ALLOWED',
  TOOL_NOT_REGISTERED: 'TOOL_NOT_REGISTERED'
};

module.exports = {
  TOOL_ERROR_CODES
};
